apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ffzpcna9m-python 
  janus-idp.io/tekton: ffzpcna9m-python
  backstage.io/kubernetes-id: ffzpcna9m-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ffzpcna9m-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml